KEY_CONFIG_FOLDER = 'media_folder'
KEY_CONFIG_DISK_VENDOR = 'disk_vendor'
KEY_CONFIG_DISK_SERIES = 'disk_series'
KEY_CONFIG_DISK_SN = 'disk_sn'
KEY_CONFIG_DISK_SPACE = 'disk_space'

KEY_PATH = 'm_path'
KEY_TYPE = 'm_type'
KEY_SIZE = 'm_size'
KEY_ADD_LIST = 'add_list'
KEY_DEL_LIST = 'del_list'
