import logging

LANGUAGE = 'zh'

LOG_LEVEL = logging.DEBUG

KEY_API_VERSION = 'api_version'
API_VERSION = '0.1'

KEY_CONFIG_FOLDER = 'media_folder'
KEY_CONFIG_DISK_VENDOR = 'disk_vendor'
KEY_CONFIG_DISK_SERIES = 'disk_series'
KEY_CONFIG_DISK_SN = 'disk_sn'
KEY_CONFIG_DISK_SPACE = 'disk_space'

KEY_PATH = 'm_path'
KEY_TYPE = 'm_type'
KEY_SIZE = 'm_size'
KEY_ADD_LIST = 'add_list'
KEY_DEL_LIST = 'del_list'

KEY_DOUBAN_API = 0
KEY_TMDB_API = 1

PATH_FILMS_IMAGES = './dynamic/films_folder/'
KEY_IMAGE_CATEGORY_POSTER = 'poster'
KEY_IMAGE_CATEGORY_LOGO = 'logo'
KEY_IMAGE_CATEGORY_BACKDROP = 'backdrop'
KEY_IMAGE_CATEGORY = [KEY_IMAGE_CATEGORY_POSTER, KEY_IMAGE_CATEGORY_LOGO, KEY_IMAGE_CATEGORY_BACKDROP]
