# Generated by Django 3.2.14 on 2022-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
